name: Build Image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-containers:
    env:
      IMAGE_REGISTRY: "ghcr.io"
      IMAGE_OWNER: "kraudcloud"
      IMAGE_NAME: "mailshuttle"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{env.IMAGE_REGISTRY}}/${{env.IMAGE_OWNER}}/${{env.IMAGE_NAME}}:latest
            ${{ github.ref_type == 'tag' && format('{0}/{1}/{2}:{3}', env.IMAGE_REGISTRY, env.IMAGE_OWNER, env.IMAGE_NAME, github.ref_name) || '' }}
